GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/66451c4f43fbade42eb17455

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ricardo",
    "tel": "2"
}

###
POST https://part3-exercise.onrender.com/api/persons
Content-Type: application/json

{
    "name": "ricardo",
    "number": "2"
}